redis:
  image: redis
  volumes:
    - [your work directory]:/data
  ports:
    - "6379:6379"
  command: redis-server
spring-boot:
  image: bankmonitor/spring-boot
  volumes:
    - [your work directory]:/app
  links:
    - redis:redis
  ports:
    - "8080:8080"
  command: java -jar ./comlis-rest-service.jar
